### ISSUE TITLE
Alter Syntax for Lambda expressions

### ISSUE THREAD

**Issue by Feliix42** [ohua-dev/alang-clike-parser#10]
The current semantic is:
```rust
let f = fn (d) {calculate(d, x)};
```

While the Rust-native way would be a construct like this:

```rust
let f = |d| calculate(d, x);
```

For further reference, you may also have a look at [the reference](https://doc.rust-lang.org/reference/expressions/closure-expr.html).

I think it would be better to alter the syntax and transition to the native closure syntax for more comfort during development.
But as of now, this is not an urgent topic.

**Comment by sertel** [comment]
Also eigentlich ist das:

```Rust
let f = |d| -> () { calculate(d,x); };
```
Obiges ist nur eine kürzere Art und Weise dies zu schreiben. Das müssen wir aber wirklich nicht unterstützen. (Zumindest nicht zu Beginn.)

**Comment by Feliix42** [comment]
Not exactly. The type of the above statements in my comment both produce a value, the return value of `calculate`. The semicolon in your example is too much.

```rust
let f = |d| -> i32 { calculate(d, x) };
```

But this is explained in the reference along with the grammar rules that form such an expression.

**Comment by sertel** [comment]
Now that is misleading Rust syntax, at least to me.

**Comment by Feliix42** [comment]
But it's the same for the original `fn` syntax, isn't it? 😄
