### ISSUE TITLE
Rusty imports

### ISSUE THREAD

**Issue by JustusAdam** [ohua-dev/alang-clike-parser#6]
Imports currently use the syntax `use sf module::qual (f1, f2);`.

Ironically enough this has just confused the hell out of *me*, which, considering that *I* wrote the bloody thing, may be an indication that its wrong to do that.

Perhaps instead we should fully commit to the syntax used by rust, which is `use sf module::qual::{f1, f2}` because that is what I just (incorrectly) assumed it was.

I'd like an opinion by @Feliix42 , whether this would invalidate too many of your test cases?

**Comment by sertel** [comment]
Even if so, they would probably be very easy to fix. So please go ahead with this.
